### ISSUE TITLE
Does not support Browsers?

### ISSUE THREAD

**Issue by mightypenguin** [joaquimserafim/base64-url#31]
With webpack v4 (angular/cli v9)
Project I get an error with using Buffer.

The Buffer class does not appear to exist in chrome.
The npm package Buffer has an issue with webpack usage.

If you can't/won't fix this, then please indicate that Browsers are unsupported.

**Comment by Rob4226** [comment]
I am getting the same error in the browser although it is working fine in my NativeScript mobile app. Is this package def not supported in the browser? Thanks.

**Comment by jonathanstanley** [comment]
similar here.  ```ReferenceError: Buffer is not defined``` upon upgrading to webpack v5.  i suspect is related to https://webpack.js.org/blog/2020-10-10-webpack-5-release/#automatic-nodejs-polyfills-removed

**Comment by joaquimserafim** [comment]
https://github.com/joaquimserafim/base64-url?tab=readme-ov-file#attention-only-tested-with-nodejs
