### ISSUE TITLE
Unescape adds 4 padding chars when string is already a multiple of 4 

### ISSUE THREAD

**Issue by bjbrewster** [joaquimserafim/base64-url#6]
```
> var b64 = require('base64-url')
> b64.unescape(b64.encode('123456789'))
'MTIzNDU2Nzg5===='
```

Can I suggest replacing `Array(5 - str.length % 4).join('=')` with `'==='.slice((str.length + 3) % 4)`?

**Comment by joaquimserafim** [comment]
Hey,

good catch 👍  I'll ship this change with the version `1.3.2` 

thanks mate

**Comment by bjbrewster** [comment]
No problem :)
